/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_test;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
import parsehtml.*;
import database.SQLiteDB;
import java.awt.Desktop;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.SQLException;


/**
 *
 * @author mobyr
 */
public class UITest extends javax.swing.JFrame {
    JPanel[] buttons;
    JPanel[] panels;
    DefaultTableModel model;
    SQLiteDB db;
    boolean isLoggedIn = false;
    KitapIslemleri k;
    String loggedMail;
    String book_url;
    /**
     * Creates new form UITest
     * @throws java.sql.SQLException
     */
    public UITest() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        db = new SQLiteDB();
        this.buttons = new JPanel[]{btn_books, btn_favorites, btn_mail, btn_register, btn_sign_in, btn_sign_out, btn_user};
        this.panels = new JPanel[]{main_pane, search_books_pane, register_pane, login_pane, favorites_pane, set_mail_pane};
        this.setNotLoggedIn();
        this.register_pane.setVisible(false);
        this.login_pane.setVisible(false);
        this.main_pane.setVisible(true);
        this.favorites_pane.setVisible(false);
        this.set_mail_pane.setVisible(false);
        this.book_table.getTableHeader().setDefaultRenderer(new HeaderColor());
        this.favorites_table.getTableHeader().setDefaultRenderer(new HeaderColor());
    }
    
    public void showBooks(String search) throws IOException
    {
        k = new KitapIslemleri();
        Parser.getBooks().clear();
        Parser[] sellers = {new TestSitesi(search), new KitapYurdu(search), new DR(search), new BKM(search), new Amazon(search), new Idefix(search)};
        k.addBooks(sellers);
        
        model = (DefaultTableModel)book_table.getModel();
        model.setRowCount(0);
        ImageIcon icon;
        JLabel img_label;
        
        for(ArrayList book: Parser.getBooks())
        {
            icon = new ImageIcon(new URL(String.valueOf(book.get(2))));
            img_label = new JLabel();
            Image img = icon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
            img_label.setIcon(new ImageIcon(img));
            float with_shipment = Float.valueOf(book.get(4).toString()) + Float.valueOf(book.get(6).toString());
            book_url = book.get(1).toString();
            Object[] eklenecek = {img_label, book.get(0), book.get(4), book.get(5), with_shipment, book_url};
            model.addRow(eklenecek);
        }
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
        book_table.setRowSorter(tr);
        ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>();
        sortKeys.add(new RowSorter.SortKey(4, SortOrder.ASCENDING));
        tr.setSortKeys(sortKeys);
        tr.sort();
    }
    
    public void showFavorites() throws SQLException
    {
        model = (DefaultTableModel)favorites_table.getModel();
        model.setRowCount(0);
        ArrayList<ArrayList<String>> favorites = db.getFavoriteInfos(loggedMail);
        if(favorites != null)
        {
            for(ArrayList<String> book: favorites)
            {
                Object[] eklenecek = {book.get(0), book.get(1), book.get(2), book.get(3), book.get(4)};
                model.addRow(eklenecek);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        main_pane = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        favorites_pane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        favorites_table = new javax.swing.JTable();
        btn_search_selected = new javax.swing.JButton();
        btn_search_selected_web = new javax.swing.JButton();
        btn_del_favorite = new javax.swing.JButton();
        lbl_favorite_msg = new javax.swing.JLabel();
        btn_update_prices = new javax.swing.JButton();
        login_pane = new javax.swing.JPanel();
        tf_mail_login = new javax.swing.JTextField();
        pf_login = new javax.swing.JPasswordField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        lbl_login_msg = new javax.swing.JLabel();
        register_pane = new javax.swing.JPanel();
        tf_name = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_surname = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf_mail = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tf_tel = new javax.swing.JTextField();
        lbl_message = new javax.swing.JLabel();
        btn_kayit_ol = new javax.swing.JButton();
        set_mail_pane = new javax.swing.JPanel();
        tf_new_mail = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        btn_save_new_mail = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        pf_new_mail = new javax.swing.JPasswordField();
        lbl_set_mail = new javax.swing.JLabel();
        side_pane = new javax.swing.JPanel();
        btn_sign_out = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_books = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_user = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_favorites = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_mail = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_sign_in = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_register = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        search_books_pane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        book_table = new javax.swing.JTable();
        tf_search = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_add_favorite = new javax.swing.JLabel();
        lbl_table_msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(51, 51, 55));
        bg.setMinimumSize(new java.awt.Dimension(1000, 700));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_pane.setBackground(new java.awt.Color(51, 51, 55));
        main_pane.setPreferredSize(new java.awt.Dimension(770, 700));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ParseHTML v1.0");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Muhammet Onur Bayraktar");

        javax.swing.GroupLayout main_paneLayout = new javax.swing.GroupLayout(main_pane);
        main_pane.setLayout(main_paneLayout);
        main_paneLayout.setHorizontalGroup(
            main_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_paneLayout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addGroup(main_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );
        main_paneLayout.setVerticalGroup(
            main_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_paneLayout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(360, 360, 360))
        );

        bg.add(main_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        favorites_pane.setBackground(new java.awt.Color(51, 51, 55));

        favorites_table.setBackground(new java.awt.Color(32, 32, 34));
        favorites_table.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        favorites_table.setForeground(new java.awt.Color(255, 255, 255));
        favorites_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap Adı", "Fiyat", "Kargo Dahil Fiyat", "Satıcı", "URL", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        favorites_table.setFillsViewportHeight(true);
        favorites_table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        favorites_table.setRowHeight(25);
        favorites_table.setShowVerticalLines(false);
        favorites_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(favorites_table);
        if (favorites_table.getColumnModel().getColumnCount() > 0) {
            favorites_table.getColumnModel().getColumn(5).setMinWidth(30);
            favorites_table.getColumnModel().getColumn(5).setPreferredWidth(30);
            favorites_table.getColumnModel().getColumn(5).setMaxWidth(40);
        }

        btn_search_selected.setBackground(new java.awt.Color(0, 0, 0));
        btn_search_selected.setForeground(new java.awt.Color(255, 255, 255));
        btn_search_selected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_search_20px.png"))); // NOI18N
        btn_search_selected.setText("Seçilen Kitabı Ara");
        btn_search_selected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_selectedActionPerformed(evt);
            }
        });

        btn_search_selected_web.setBackground(new java.awt.Color(0, 0, 0));
        btn_search_selected_web.setForeground(new java.awt.Color(255, 255, 255));
        btn_search_selected_web.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_website_20px.png"))); // NOI18N
        btn_search_selected_web.setText("Siteye Git");
        btn_search_selected_web.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_selected_webActionPerformed(evt);
            }
        });

        btn_del_favorite.setBackground(new java.awt.Color(0, 0, 0));
        btn_del_favorite.setForeground(new java.awt.Color(255, 255, 255));
        btn_del_favorite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_delete_20px.png"))); // NOI18N
        btn_del_favorite.setText("Favorilerden Çıkar");
        btn_del_favorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_del_favoriteActionPerformed(evt);
            }
        });

        lbl_favorite_msg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbl_favorite_msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_update_prices.setBackground(new java.awt.Color(0, 0, 0));
        btn_update_prices.setForeground(new java.awt.Color(255, 255, 255));
        btn_update_prices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_available_updates_20px.png"))); // NOI18N
        btn_update_prices.setText("Fiyat Güncelle");
        btn_update_prices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_pricesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout favorites_paneLayout = new javax.swing.GroupLayout(favorites_pane);
        favorites_pane.setLayout(favorites_paneLayout);
        favorites_paneLayout.setHorizontalGroup(
            favorites_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(favorites_paneLayout.createSequentialGroup()
                .addGroup(favorites_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(favorites_paneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(favorites_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, favorites_paneLayout.createSequentialGroup()
                                .addComponent(lbl_favorite_msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_update_prices)
                                .addGap(313, 313, 313))
                            .addComponent(jScrollPane2)))
                    .addGroup(favorites_paneLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btn_del_favorite)
                        .addGap(105, 105, 105)
                        .addComponent(btn_search_selected_web)
                        .addGap(94, 94, 94)
                        .addComponent(btn_search_selected)
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        favorites_paneLayout.setVerticalGroup(
            favorites_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(favorites_paneLayout.createSequentialGroup()
                .addGroup(favorites_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(favorites_paneLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbl_favorite_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, favorites_paneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update_prices)
                        .addGap(18, 18, 18)))
                .addGroup(favorites_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_search_selected)
                    .addComponent(btn_search_selected_web)
                    .addComponent(btn_del_favorite))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(favorites_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 770, 700));

        login_pane.setBackground(new java.awt.Color(51, 51, 55));
        login_pane.setPreferredSize(new java.awt.Dimension(770, 700));

        tf_mail_login.setBackground(new java.awt.Color(0, 0, 0));
        tf_mail_login.setForeground(new java.awt.Color(255, 255, 255));

        pf_login.setBackground(new java.awt.Color(0, 0, 0));
        pf_login.setForeground(new java.awt.Color(255, 255, 255));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("E-Mail");

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Parola");

        btn_login.setBackground(new java.awt.Color(0, 0, 0));
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_login_20px_1.png"))); // NOI18N
        btn_login.setText("Giriş Yap");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout login_paneLayout = new javax.swing.GroupLayout(login_pane);
        login_pane.setLayout(login_paneLayout);
        login_paneLayout.setHorizontalGroup(
            login_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_paneLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(login_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_login_msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(login_paneLayout.createSequentialGroup()
                        .addGroup(login_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(login_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_mail_login)
                            .addComponent(pf_login, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(login_paneLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btn_login)))
                        .addGap(0, 285, Short.MAX_VALUE)))
                .addContainerGap())
        );
        login_paneLayout.setVerticalGroup(
            login_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_paneLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(login_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_mail_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(login_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_login_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_login)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        bg.add(login_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 770, 700));

        register_pane.setBackground(new java.awt.Color(51, 51, 55));

        tf_name.setBackground(new java.awt.Color(0, 0, 0));
        tf_name.setForeground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Adınız");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Soyadınız");

        tf_surname.setBackground(new java.awt.Color(0, 0, 0));
        tf_surname.setForeground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("E-Posta Adresiniz");

        tf_mail.setBackground(new java.awt.Color(0, 0, 0));
        tf_mail.setForeground(new java.awt.Color(255, 255, 255));

        pf_password.setBackground(new java.awt.Color(0, 0, 0));
        pf_password.setForeground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Parolanız");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Telefon Numaranız");

        tf_tel.setBackground(new java.awt.Color(0, 0, 0));
        tf_tel.setForeground(new java.awt.Color(255, 255, 255));

        lbl_message.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbl_message.setForeground(new java.awt.Color(102, 204, 0));

        btn_kayit_ol.setBackground(new java.awt.Color(0, 0, 0));
        btn_kayit_ol.setForeground(new java.awt.Color(255, 255, 255));
        btn_kayit_ol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_save_20px_1.png"))); // NOI18N
        btn_kayit_ol.setText("Kayıt Ol");
        btn_kayit_ol.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btn_kayit_ol.setBorderPainted(false);
        btn_kayit_ol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayit_olActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout register_paneLayout = new javax.swing.GroupLayout(register_pane);
        register_pane.setLayout(register_paneLayout);
        register_paneLayout.setHorizontalGroup(
            register_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_paneLayout.createSequentialGroup()
                .addGroup(register_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(register_paneLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel19)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, register_paneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(register_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)))
                .addGroup(register_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(register_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_tel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tf_surname, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(tf_name)
                        .addComponent(tf_mail, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(pf_password))
                    .addComponent(btn_kayit_ol)
                    .addComponent(lbl_message, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        register_paneLayout.setVerticalGroup(
            register_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_paneLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(register_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(register_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(register_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(register_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(register_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_message, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_kayit_ol)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        bg.add(register_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 770, 700));

        set_mail_pane.setBackground(new java.awt.Color(51, 51, 55));

        tf_new_mail.setBackground(new java.awt.Color(0, 0, 0));
        tf_new_mail.setForeground(new java.awt.Color(255, 255, 255));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Yeni E-Posta Adresiniz");

        btn_save_new_mail.setBackground(new java.awt.Color(0, 0, 0));
        btn_save_new_mail.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_new_mail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_save_20px_1.png"))); // NOI18N
        btn_save_new_mail.setText("Kaydet");
        btn_save_new_mail.setMaximumSize(new java.awt.Dimension(93, 29));
        btn_save_new_mail.setMinimumSize(new java.awt.Dimension(93, 29));
        btn_save_new_mail.setPreferredSize(new java.awt.Dimension(93, 29));
        btn_save_new_mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_save_new_mailMouseClicked(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Parola");

        pf_new_mail.setBackground(new java.awt.Color(0, 0, 0));
        pf_new_mail.setForeground(new java.awt.Color(255, 255, 255));

        lbl_set_mail.setForeground(new java.awt.Color(255, 255, 255));
        lbl_set_mail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_set_mail.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout set_mail_paneLayout = new javax.swing.GroupLayout(set_mail_pane);
        set_mail_pane.setLayout(set_mail_paneLayout);
        set_mail_paneLayout.setHorizontalGroup(
            set_mail_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(set_mail_paneLayout.createSequentialGroup()
                .addGroup(set_mail_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(set_mail_paneLayout.createSequentialGroup()
                        .addGroup(set_mail_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(set_mail_paneLayout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addGroup(set_mail_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(set_mail_paneLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_new_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(set_mail_paneLayout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pf_new_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(set_mail_paneLayout.createSequentialGroup()
                                .addGap(329, 329, 329)
                                .addComponent(btn_save_new_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 320, Short.MAX_VALUE))
                    .addGroup(set_mail_paneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_set_mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        set_mail_paneLayout.setVerticalGroup(
            set_mail_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(set_mail_paneLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(set_mail_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_new_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(set_mail_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(pf_new_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btn_save_new_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lbl_set_mail)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        bg.add(set_mail_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 770, 700));

        side_pane.setBackground(new java.awt.Color(32, 32, 34));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_sign_out.setBackground(new java.awt.Color(71, 71, 75));
        btn_sign_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sign_outMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_exit_30px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Oturumu Kapat");

        javax.swing.GroupLayout btn_sign_outLayout = new javax.swing.GroupLayout(btn_sign_out);
        btn_sign_out.setLayout(btn_sign_outLayout);
        btn_sign_outLayout.setHorizontalGroup(
            btn_sign_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_sign_outLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        btn_sign_outLayout.setVerticalGroup(
            btn_sign_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_sign_outLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_sign_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 230, 50));

        btn_exit.setBackground(new java.awt.Color(32, 32, 34));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_exit_sign_30px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Çıkış Yap");

        javax.swing.GroupLayout btn_exitLayout = new javax.swing.GroupLayout(btn_exit);
        btn_exit.setLayout(btn_exitLayout);
        btn_exitLayout.setHorizontalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_exitLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        btn_exitLayout.setVerticalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 230, 50));

        btn_books.setBackground(new java.awt.Color(32, 32, 34));
        btn_books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_booksMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_book_30px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kitap Ara");

        javax.swing.GroupLayout btn_booksLayout = new javax.swing.GroupLayout(btn_books);
        btn_books.setLayout(btn_booksLayout);
        btn_booksLayout.setHorizontalGroup(
            btn_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_booksLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        btn_booksLayout.setVerticalGroup(
            btn_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_booksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 230, 50));

        btn_user.setBackground(new java.awt.Color(32, 32, 34));
        btn_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_userMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_user_30px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kullanıcı İşlemleri");

        javax.swing.GroupLayout btn_userLayout = new javax.swing.GroupLayout(btn_user);
        btn_user.setLayout(btn_userLayout);
        btn_userLayout.setHorizontalGroup(
            btn_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_userLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        btn_userLayout.setVerticalGroup(
            btn_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 230, 50));

        btn_favorites.setBackground(new java.awt.Color(71, 71, 75));
        btn_favorites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_favoritesMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_star_30px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Favoriler");

        javax.swing.GroupLayout btn_favoritesLayout = new javax.swing.GroupLayout(btn_favorites);
        btn_favorites.setLayout(btn_favoritesLayout);
        btn_favoritesLayout.setHorizontalGroup(
            btn_favoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_favoritesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        btn_favoritesLayout.setVerticalGroup(
            btn_favoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_favoritesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_favorites, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 230, 50));

        btn_mail.setBackground(new java.awt.Color(71, 71, 75));
        btn_mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mailMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_secured_letter_30px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("E-Posta Değiştir");

        javax.swing.GroupLayout btn_mailLayout = new javax.swing.GroupLayout(btn_mail);
        btn_mail.setLayout(btn_mailLayout);
        btn_mailLayout.setHorizontalGroup(
            btn_mailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_mailLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        btn_mailLayout.setVerticalGroup(
            btn_mailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_mailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 230, 50));

        btn_sign_in.setBackground(new java.awt.Color(32, 32, 34));
        btn_sign_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_sign_inMousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_login_30px.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Giriş Yap");

        javax.swing.GroupLayout btn_sign_inLayout = new javax.swing.GroupLayout(btn_sign_in);
        btn_sign_in.setLayout(btn_sign_inLayout);
        btn_sign_inLayout.setHorizontalGroup(
            btn_sign_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_sign_inLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_sign_inLayout.setVerticalGroup(
            btn_sign_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(btn_sign_inLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        side_pane.add(btn_sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, 50));

        btn_register.setBackground(new java.awt.Color(32, 32, 34));
        btn_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_registerMousePressed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_registration_30px.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Kayıt Ol");

        javax.swing.GroupLayout btn_registerLayout = new javax.swing.GroupLayout(btn_register);
        btn_register.setLayout(btn_registerLayout);
        btn_registerLayout.setHorizontalGroup(
            btn_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_registerLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        btn_registerLayout.setVerticalGroup(
            btn_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_registerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 50));

        bg.add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 700));

        search_books_pane.setBackground(new java.awt.Color(51, 51, 55));
        search_books_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setOpaque(false);

        book_table.setBackground(new java.awt.Color(32, 32, 34));
        book_table.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        book_table.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        book_table.setForeground(new java.awt.Color(255, 255, 255));
        book_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resim", "Kitap Adı", "Fiyat", "Satıcı", "Kargo Dahil Fiyat", "URL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        book_table.setFillsViewportHeight(true);
        book_table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        book_table.setRowHeight(25);
        book_table.setShowVerticalLines(false);
        book_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(book_table);
        if (book_table.getColumnModel().getColumnCount() > 0) {
            book_table.getColumnModel().getColumn(0).setMinWidth(100);
            book_table.getColumnModel().getColumn(0).setMaxWidth(100);
            book_table.getColumnModel().getColumn(2).setMinWidth(50);
            book_table.getColumnModel().getColumn(2).setMaxWidth(50);
            book_table.getColumnModel().getColumn(3).setMinWidth(90);
            book_table.getColumnModel().getColumn(3).setMaxWidth(90);
            book_table.getColumnModel().getColumn(4).setMinWidth(150);
            book_table.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        search_books_pane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 107, 760, 580));

        tf_search.setBackground(new java.awt.Color(32, 32, 34));
        tf_search.setForeground(new java.awt.Color(255, 255, 255));
        search_books_pane.add(tf_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 140, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Aranacak Kitap");
        search_books_pane.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_search_20px.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
        });
        search_books_pane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 20, 20));

        btn_add_favorite.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_favorite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_test/images/icons8_star_20px.png"))); // NOI18N
        btn_add_favorite.setText("Favorilere Ekle");
        btn_add_favorite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_add_favoriteMousePressed(evt);
            }
        });
        search_books_pane.add(btn_add_favorite, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, 20));
        search_books_pane.add(lbl_table_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 270, 20));

        bg.add(search_books_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 770, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_booksMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_booksMousePressed
        hidePanels(search_books_pane);
        this.search_books_pane.setVisible(true);
        setColor(this.btn_books);
        this.btn_favorites.setVisible(false);
        this.btn_mail.setVisible(false);
        this.btn_sign_out.setVisible(false);
        this.resetColors(btn_books);
        if(isLoggedIn)
        {
            btn_add_favorite.setVisible(true);
        }
        
        else
        {
            btn_add_favorite.setVisible(false);
        }
        
        ImageIcon star = new ImageIcon("src/interface_test/images/icons8_star_20px.png");
        star.getImage().flush();
        btn_add_favorite.setIcon(star);
        lbl_table_msg.setText("");
    }//GEN-LAST:event_btn_booksMousePressed

    private void btn_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMousePressed
        setColor(this.btn_user);
        this.btn_favorites.setVisible(true);
        this.btn_mail.setVisible(true);
        this.btn_sign_out.setVisible(true);
        resetColors(btn_user);
    }//GEN-LAST:event_btn_userMousePressed

    private void btn_registerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMousePressed
        setColor(this.btn_register);
        this.btn_favorites.setVisible(false);
        this.btn_mail.setVisible(false);
        this.btn_sign_out.setVisible(false);
        this.resetColors(btn_register);
        hidePanels(register_pane);
        register_pane.setVisible(true);
    }//GEN-LAST:event_btn_registerMousePressed

    private void btn_sign_inMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sign_inMousePressed
        setColor(this.btn_sign_in);
        this.btn_favorites.setVisible(false);
        this.btn_mail.setVisible(false);
        this.btn_sign_out.setVisible(false);
        this.resetColors(btn_sign_in);
        hidePanels(login_pane);
        login_pane.setVisible(true);
    }//GEN-LAST:event_btn_sign_inMousePressed

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MousePressed
        ImageIcon star = new ImageIcon("src/interface_test/images/icons8_star_20px.png");
        star.getImage().flush();
        btn_add_favorite.setIcon(star);
        String search = this.tf_search.getText();
        this.book_table.getColumn("Resim").setCellRenderer(new CellRenderer());
        try
        {
            this.showBooks(search);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(UITest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel18MousePressed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_bgMouseDragged

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void btn_kayit_olActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayit_olActionPerformed
        String f_name = tf_name.getText();
        String l_name = tf_surname.getText();
        String mail = tf_mail.getText();
        String password = String.valueOf(pf_password.getPassword());
        String phone = tf_tel.getText();
        
        if(f_name.isEmpty() | l_name.isEmpty() | mail.isEmpty() | password.isEmpty() | phone.isEmpty())
        {
            lbl_message.setForeground(Color.red);
            lbl_message.setText("Alanlar boş bırakılmamalıdır.");
        }
        
        else
        {
            try 
            {
                if(db.isUniqueMail(mail))
                {
                    db.addUser(f_name, l_name, mail, password, phone);
                    lbl_message.setForeground(Color.green);
                    lbl_message.setText("Başarıyla kayıt oldunuz.");
                    this.tf_name.setText("");
                    this.tf_surname.setText("");
                    this.tf_mail.setText("");
                    this.pf_password.setText("");
                    this.tf_tel.setText("");
                }
                
                else
                {
                    lbl_message.setForeground(Color.red);
                    lbl_message.setText("Girilen e-posta adresi zaten kayıtlı!");
                }
            } 
            
            catch (SQLException ex) 
            {
                Logger.getLogger(UITest.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_kayit_olActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String mail = tf_mail_login.getText();
        String password = String.valueOf(pf_login.getPassword());
        try 
        {
            if(mail.isEmpty() || password.isEmpty())
            {
                lbl_login_msg.setForeground(Color.red);
                lbl_login_msg.setText("Alanların hepsi doldurulmalıdır.");
            }
            
            else
            {
                if(db.isRegistered(mail, password))
                {
                    this.isLoggedIn = true;
                    btn_sign_in.setVisible(false);
                    btn_register.setVisible(false);
                    setLoggedIn();
                    hidePanels(search_books_pane);
                    btn_favorites.setVisible(false);
                    btn_mail.setVisible(false);
                    btn_sign_out.setVisible(false);
                    btn_add_favorite.setVisible(true);
                    this.loggedMail = mail;
                }
                
                else
                {
                    lbl_login_msg.setForeground(Color.red);
                    lbl_login_msg.setText("Girilen bilgilere sahip bir kullanıcı bulunamadı.");
                }
            }
        } 
        
        catch (SQLException ex) 
        {
            Logger.getLogger(UITest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_add_favoriteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_favoriteMousePressed
        
        if(model == null || model.getRowCount() == 0)
        {
            lbl_table_msg.setForeground(Color.red);
            lbl_table_msg.setText("Önce bir arama yapmalısınız.");
        }

        else
        {
            int index = book_table.getSelectedRow();
            if(index == -1)
            {
                lbl_table_msg.setForeground(Color.red);
                lbl_table_msg.setText("Önce bir kitabın üstüne tıklamalısınız."); 
            }
            
            else
            {
                float last_price = (Float)book_table.getValueAt(index, 2);
                float shipment_and_price = (Float)book_table.getValueAt(index, 4);
                String seller = book_table.getValueAt(index, 3).toString();
                String url = book_table.getValueAt(index, 5).toString();
                String text = book_table.getValueAt(index, 1).toString();
                System.out.println(last_price);

                try 
                {
                    boolean isAdded = db.addFavorite(loggedMail, text, last_price, shipment_and_price, seller, url);
                    if(isAdded)
                    {
                        ImageIcon filled_star = new ImageIcon("src/interface_test/images/icons8_star_filled_20px.png");
                        filled_star.getImage().flush();
                        btn_add_favorite.setIcon(filled_star);
                        lbl_table_msg.setForeground(Color.green);
                        lbl_table_msg.setText("Kitap başarıyla favorilerinize eklendi.");
                    }

                    else
                    {
                        lbl_table_msg.setForeground(Color.red);
                        lbl_table_msg.setText("Kitap zaten favorilerinizde ekli.");
                    }
                }

                catch (SQLException ex) 
                {
                    ex.toString();
                    Logger.getLogger(UITest.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btn_add_favoriteMousePressed

    private void btn_favoritesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_favoritesMousePressed
        try 
        {
            setColor(btn_favorites);
            resetColors(btn_favorites);
            hidePanels(favorites_pane);
            this.showFavorites();
            favorites_pane.setVisible(true);
        } 
        
        catch (SQLException ex) 
        {
            Logger.getLogger(UITest.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btn_favoritesMousePressed

    private void btn_search_selectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_selectedActionPerformed
        try 
        {
            int selected_row = favorites_table.getSelectedRow();
            String search = favorites_table.getValueAt(selected_row, 0).toString();
            hidePanels(search_books_pane);
            btn_favorites.setVisible(false);
            btn_mail.setVisible(false);
            btn_sign_out.setVisible(false);
            this.book_table.getColumn("Resim").setCellRenderer(new CellRenderer());
            showBooks(search);
            this.tf_search.setText(search);
            resetColors(btn_books);
            setColor(btn_books);
            search_books_pane.setVisible(true);
        }
        
        catch (IOException ex) 
        {
            Logger.getLogger(UITest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_search_selectedActionPerformed

    private void btn_del_favoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_del_favoriteActionPerformed
        int selected_row = favorites_table.getSelectedRow();
        
        try 
        {
            int book_id = db.getBookID(favorites_table.getValueAt(selected_row, 4).toString());
            db.deleteFavorite(loggedMail, book_id);
            showFavorites();
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(UITest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_del_favoriteActionPerformed

    private void btn_search_selected_webActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_selected_webActionPerformed
        int selected_row = favorites_table.getSelectedRow();
        String search = favorites_table.getValueAt(selected_row, 4).toString();
        try 
        {
            Desktop.getDesktop().browse(new URI(search));
        } 
        
        catch (URISyntaxException | IOException ex) {
            Logger.getLogger(UITest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_search_selected_webActionPerformed

    private void btn_mailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mailMouseClicked
        setColor(btn_mail);
        resetColors(btn_mail);
        hidePanels(set_mail_pane);
        this.set_mail_pane.setVisible(true);
    }//GEN-LAST:event_btn_mailMouseClicked

    private void btn_save_new_mailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_save_new_mailMouseClicked
        String new_mail = this.tf_new_mail.getText();
        String password = String.valueOf(this.pf_new_mail.getPassword());
        
        try 
        {
            if(db.isRegistered(loggedMail, password))
            {
                db.setMail(loggedMail, new_mail);
                lbl_set_mail.setForeground(Color.green);
                lbl_set_mail.setText("E-Posta değiştirme işlemi başarılı oldu.");
                this.tf_new_mail.setText("");
                this.pf_new_mail.setText("");
            }
            
            else
            {
                lbl_set_mail.setForeground(Color.red);
                lbl_set_mail.setText("Parolanız yanlış.");
            }
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(UITest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_save_new_mailMouseClicked

    private void btn_sign_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sign_outMouseClicked
        this.loggedMail = "";
        setNotLoggedIn();
        this.tf_mail_login.setText("");
        this.pf_login.setText("");
        hidePanels(login_pane);
        isLoggedIn = false;
        this.main_pane.setVisible(true);
        model.setRowCount(0);
    }//GEN-LAST:event_btn_sign_outMouseClicked

    private void btn_update_pricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_pricesActionPerformed
             try
        {
            db.checkDiscount(loggedMail);
            showFavorites();
        }
        
        catch (SQLException | IOException ex) {
                Logger.getLogger(UITest.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btn_update_pricesActionPerformed

    int xx ,xy;
    
    void setColor(JPanel panel)
    {
        panel.setBackground(new Color(101, 101, 105));
    }
    
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(32, 32, 34));
    }
    
    void resetColors(JPanel button)
    {
        for(JPanel btn: this.buttons)
        {
            if(!btn.equals(button))
            {
                this.resetColor(btn);
            }
        }
    }
    
    void hidePanels(JPanel panel)
    {
        for(JPanel pane: this.panels)
        {
            if(!pane.equals(panel))
            {
                pane.setVisible(false);
            }
        }
    }
    
    final void setNotLoggedIn()
    {
        btn_sign_in.setVisible(true);
        btn_sign_in.setBounds(0, 300, 230, 50);
        btn_register.setVisible(true);
        btn_books.setVisible(true);
        btn_user.setVisible(false);
        search_books_pane.setVisible(false);
        btn_favorites.setVisible(false);
        btn_add_favorite.setVisible(false);
        btn_mail.setVisible(false);
        btn_sign_out.setVisible(false);
        tf_search.setText("");
    }
    
    final void setLoggedIn()
    {
        btn_user.setVisible(true);
        search_books_pane.setVisible(true);
        btn_favorites.setVisible(true);
        btn_mail.setVisible(true);
        btn_sign_out.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UITest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UITest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UITest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UITest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new UITest().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UITest.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    

        
 
    
    
        class CellRenderer implements TableCellRenderer {
 
        @Override
        public Component getTableCellRendererComponent(JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {
 
            TableColumn tb = book_table.getColumn("Resim");
            tb.setMaxWidth(60);
            tb.setMinWidth(60);
 
            book_table.setRowHeight(60);
            return (Component) value;
        }
 
    }
        
        public static class HeaderColor extends DefaultTableCellRenderer
    {
        public HeaderColor()
        {
            setOpaque(true);
        }
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused, int row, int column)
        {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);
            setBackground(new java.awt.Color(40, 40, 42));
            setForeground(new Color(255, 255, 255));
            return this;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JTable book_table;
    private javax.swing.JLabel btn_add_favorite;
    private javax.swing.JPanel btn_books;
    private javax.swing.JButton btn_del_favorite;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JPanel btn_favorites;
    private javax.swing.JButton btn_kayit_ol;
    private javax.swing.JButton btn_login;
    private javax.swing.JPanel btn_mail;
    private javax.swing.JPanel btn_register;
    private javax.swing.JButton btn_save_new_mail;
    private javax.swing.JButton btn_search_selected;
    private javax.swing.JButton btn_search_selected_web;
    private javax.swing.JPanel btn_sign_in;
    private javax.swing.JPanel btn_sign_out;
    private javax.swing.JButton btn_update_prices;
    private javax.swing.JPanel btn_user;
    private javax.swing.JPanel favorites_pane;
    private javax.swing.JTable favorites_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_favorite_msg;
    private javax.swing.JLabel lbl_login_msg;
    private javax.swing.JLabel lbl_message;
    private javax.swing.JLabel lbl_set_mail;
    private javax.swing.JLabel lbl_table_msg;
    private javax.swing.JPanel login_pane;
    private javax.swing.JPanel main_pane;
    private javax.swing.JPasswordField pf_login;
    private javax.swing.JPasswordField pf_new_mail;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPanel register_pane;
    private javax.swing.JPanel search_books_pane;
    private javax.swing.JPanel set_mail_pane;
    private javax.swing.JPanel side_pane;
    private javax.swing.JTextField tf_mail;
    private javax.swing.JTextField tf_mail_login;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_new_mail;
    private javax.swing.JTextField tf_search;
    private javax.swing.JTextField tf_surname;
    private javax.swing.JTextField tf_tel;
    // End of variables declaration//GEN-END:variables
}
